### ISSUE TITLE
Fix for HnH?

### ISSUE THREAD

**Issue by Digitalroot** [cchin11/ValheimCreativeMode#2]
With the Console to Term changes. Do you plan to update the mod? If not I will update and post a change.

**Comment by cchin11** [comment]
Hi @Digitalroot , I haven't had time to take a look at Hearth and Stone yet. But I am planning on updating the mod if possible.

**Comment by Digitalroot** [comment]
I am just happy you are still active. I'll take a look and if I can fix it, I'll open a PR.

**Comment by cchin11** [comment]
Fixed for HnH - and added some QOL commands.
